config/routes.rb
Rails.application.routes.draw do
  resources :industries
  resources :startups
  get 'profile/show'

  get 'static/about'

  get 'home/index'
  devise_for :greens

  get 'about' => 'static#about', as: :about
  get 'greens' => 'static#greens', as: :greens
  get 'profile' => 'profile#show', as: :profile

  root 'home#index'

  resources :projects

end

app/models/startup.rb
class Startup < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/person-flat.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

    belongs_to :green
    belongs_to :industry
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :set_startup, only: [:show, :edit, :update, :destroy]

  # GET /startups
  # GET /startups.json
  def index
    @startups = Startup.all
  end

  # GET /startups/1
  # GET /startups/1.json
  def show
  end

  # GET /startups/new
  def new
    @startup = Startup.new
  end

  # GET /startups/1/edit
  def edit
  end

  # POST /startups
  # POST /startups.json
  def create
    @startup = Startup.new(startup_params)

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup, notice: 'Startup was successfully created.' }
        format.json { render :show, status: :created, location: @startup }
      else
        format.html { render :new }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /startups/1
  # PATCH/PUT /startups/1.json
  def update
    respond_to do |format|
      if @startup.update(startup_params)
        format.html { redirect_to @startup, notice: 'Startup was successfully updated.' }
        format.json { render :show, status: :ok, location: @startup }
      else
        format.html { render :edit }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /startups/1
  # DELETE /startups/1.json
  def destroy
    @startup.destroy
    respond_to do |format|
      format.html { redirect_to startups_url, notice: 'Startup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_startup
      @startup = Startup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def startup_params
      params.require(:startup).permit(:name, :website, :facebook, :twitter, :email, :about, :founded, :days_at_ihub, :employees, :image)
    end
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/views/startups/_form.html.haml
= form_for @startup do |f|
  - if @startup.errors.any?
    #error_explanation
      %h2= "#{pluralize(@startup.errors.count, "error")} prohibited this startup from being saved:"
      %ul
        - @startup.errors.full_messages.each do |msg|
          %li= msg
  .field
    = image_tag @startup.image.url(:medium) 
    %br/
    = f.file_field :image
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :founder
    = f.collection_select :green_id, Green.all, :id, :username
    -#= collection_select(:startup, :green_id, Green.all, :id, :username, {}, {:multiple => false})
  .field
    = f.label :Industry
    = f.collection_select :industry_id, Industry.all, :id, :name
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :facebook
    = f.text_field :facebook
  .field
    = f.label :twitter
    = f.text_field :twitter
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :about
    = f.text_area :about
  .field
    = f.label :founded
    = f.number_field :founded
  .field
    = f.label :days_at_ihub
    = f.number_field :days_at_ihub
  .field
    = f.label :employees
    = f.number_field :employees
  .actions
    = f.submit 'Save'

app/views/startups/edit.html.haml
%h1 Editing startup

= render 'form'

= link_to 'Show', @startup
\|
= link_to 'Back', startups_path

app/views/startups/index.html.haml
%h1 Startups
= link_to 'New Startup', new_startup_path

%br 

%table
  %tbody
    - @startups.each do |startup|
      %tr
        %td= link_to (image_tag startup.image.url(:thumb)), startup
        %td= link_to startup.name, startup       

%br

app/views/startups/new.html.haml
%h1 New startup

= render 'form'

= link_to 'Back', startups_path

app/views/startups/show.html.haml
%p#notice= notice
%p
  = image_tag @startup.image.url(:medium)
%p
  %b Name:
  = @startup.name
%p
  %b Website:
  = @startup.website
%p
  %b Facebook:
  = @startup.facebook
%p
  %b Twitter:
  = @startup.twitter
%p
  %b Email:
  = @startup.email
%p
  %b About:
  = @startup.about
%p
  %b Founded:
  = @startup.founded
%p
  %b Days at ihub:
  = @startup.days_at_ihub
%p
  %b Employees:
  = @startup.employees

= link_to 'Edit', edit_startup_path(@startup)
\|
= link_to 'Back', startups_path
\|
= link_to 'Delete', @startup, :method => :delete, :data => { :confirm => 'Are you sure?' }