config/routes.rb
Rails.application.routes.draw do
  resources :industries
  resources :startups
  get 'profile/show'

  get 'static/about'

  get 'home/index'
  devise_for :greens

  get 'about' => 'static#about', as: :about
  get 'greens' => 'static#greens', as: :greens
  get 'profile' => 'profile#show', as: :profile

  root 'home#index'

  resources :projects

end

app/models/industry.rb
class Industry < ActiveRecord::Base
	has_many :startups
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :set_industry, only: [:show, :edit, :update, :destroy]

  # GET /industries
  # GET /industries.json
  def index
    @industries = Industry.all
  end

  # GET /industries/1
  # GET /industries/1.json
  def show
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries
  # POST /industries.json
  def create
    @industry = Industry.new(industry_params)

    respond_to do |format|
      if @industry.save
        format.html { redirect_to @industry, notice: 'Industry was successfully created.' }
        format.json { render :show, status: :created, location: @industry }
      else
        format.html { render :new }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /industries/1
  # PATCH/PUT /industries/1.json
  def update
    respond_to do |format|
      if @industry.update(industry_params)
        format.html { redirect_to @industry, notice: 'Industry was successfully updated.' }
        format.json { render :show, status: :ok, location: @industry }
      else
        format.html { render :edit }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1
  # DELETE /industries/1.json
  def destroy
    @industry.destroy
    respond_to do |format|
      format.html { redirect_to industries_url, notice: 'Industry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def industry_params
      params.require(:industry).permit(:name)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.haml
= form_for @industry do |f|
  - if @industry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@industry.errors.count, "error")} prohibited this industry from being saved:"
      %ul
        - @industry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.number_field :name
  .actions
    = f.submit 'Save'

app/views/industries/edit.html.haml
%h1 Editing industry

= render 'form'

= link_to 'Show', @industry
\|
= link_to 'Back', industries_path

app/views/industries/index.html.haml
%h1 Listing industries

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @industries.each do |industry|
      %tr
        %td= industry.name
        %td= link_to 'Show', industry
        %td= link_to 'Edit', edit_industry_path(industry)
        %td= link_to 'Destroy', industry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Industry', new_industry_path

app/views/industries/new.html.haml
%h1 New industry

= render 'form'

= link_to 'Back', industries_path

app/views/industries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @industry.name

= link_to 'Edit', edit_industry_path(@industry)
\|
= link_to 'Back', industries_path