config/routes.rb
Rails.application.routes.draw do
  resources :industries
  resources :startups
  get 'profile/show'

  get 'static/about'

  get 'home/index'
  devise_for :greens

  get 'about' => 'static#about', as: :about
  get 'greens' => 'static#greens', as: :greens
  get 'profile' => 'profile#show', as: :profile

  root 'home#index'

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :green
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_green!
  def new
  	@project = Project.new
  end

  def create
  	@project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to new_project_path, notice: 'Photo was successfully created.' }
        format.json { render :new, status: :created, location: @project }
      else
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    
  end

  private
  	def project_params
  		params.require(:project).permit(:name, :description, :link, :green_id)
  	end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/projects/_form.html.haml
.ui.grid
	.four.wide.column
		.ui.form
			= form_for @project do |f|
				.field
					= f.label :name
					%br/
					= f.text_field :name, autofocus: true
				.field
					= f.label :description
					%br/
					= f.text_area :description
				.field
					= f.label :link
					%br/
					= f.text_field :link

				= f.hidden_field :green_id, value: current_green.id

				.field
					= f.submit "Save Project", class: 'ui button'
	.twelve.wide.column


		

app/views/projects/_project_items.html.haml
hhhh

app/views/projects/create.js.haml
/ $(".cart-text").html("#{escape_javascript(render 'projects/project_items')}")

app/views/projects/new.html.haml
.container
  .col-md-3
    =render 'layouts/navigation'
  .col-md-9
    = render 'form'